apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: lvms-operator-webhook-server-cert
  creationTimestamp: null
  name: lvms-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: lvms-operator
status:
  loadBalancer: {}
