
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: lvms-operator
    app.kubernetes.io/part-of: lvms-provisioner
  name: lvms-operator-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: topolvm-metrics
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
    - path: /metrics
      port: lvms-metrics
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/compose: metrics
