apiVersion: v1
kind: Service
metadata:
  name: lvms-node-metrics
  namespace: system
  labels:
    app.kubernetes.io/compose: metrics
    app.kubernetes.io/part-of: lvms-provisioner
spec:
  selector:
    exporter: lvms-operator
  ports:
    - name: lvms-metrics
      protocol: TCP
      port: 23532
      targetPort: 23532
